export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';
export const CLEAR_FETCH = 'CLEAR FETCH';